# Generated by Django 5.0.3 on 2024-03-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='Dietary_Restrictions',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
