# Generated by Django 5.0.3 on 2024-03-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_prompts_dietary_restrictions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompts',
            name='Dietary_Restrictions',
        ),
    ]
